### ISSUE TITLE
wiadomosci.tvp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [zacny/voddownloader#17]
@zacny da rade obejsc geo-lock na wiadomosciach?

caly czas sciaga mi ten filmik:
http://s.tvp.pl/files/player/video/material_niedostepny.mp4

browser: firefox 67.0.3
plugin: 5.8.3

**Comment by zacny** [comment]
Potrzebuję więcej informacji? Najlepiej kod strony z konsoli developersiej po dociągnięciu wszystkich skladowych. Czy wyświetla się lista dostępnych pozycji w tabelce i czy takie coś dzieje się przy kliknięciu na dowolną z pozycję?
@funplayertv też masz coś takiego?

**Comment by funplayertv** [comment]
@zacny owszem i raczej na pierwszy rzut oka nie jest to do ominięcia, dlatego nawet o tym nie pisałem, bo po wpisaniu ID w API i zaciągnięciu jsona, ten link juz jest wrzucany (do tego filmiku o materiale niedostępnym), aleeee u mnie np. wiadomości działały i nie każdy materiał był w ten sposób zablokowany, ale były owszem materiały blokowane... dokładnie w ten sam sposób jak opisany tutaj... nie mam jak teraz wrzucić Ci kodu www, ale moze spróboj odpalic portable Tor Browser, albo vpn HOLA czy cos i sprawdzisz po swojej stronie?

**Comment by xxcriticxx** [comment]
test link:
https://vod.tvp.pl/video/wiadomosci,19062019-1930,42862438

lista:
![Capture2](https://user-images.githubusercontent.com/15007183/59839205-49ebc180-931e-11e9-89b4-6d1742f577d1.PNG)

tampermonkey error:
![Capture3](https://user-images.githubusercontent.com/15007183/59839280-64be3600-931e-11e9-9492-091eedc7b66b.PNG)

console:
https://pastebin.com/1gtpSQ9H

**Comment by xxcriticxx** [comment]
Poprawiłem ten błąd w tampermonkey ale nic nie pomaga dalej widzę tylko jedna pozycje do ściągnięcia

**Comment by funplayertv** [comment]
@xxcriticxx  potrzeby jest kod całej www, z konsoli programowania, czyli jak kliaksz f12 i zakłądka inspektora to cały kod html wrzuc do pastebin'a

**Comment by funplayertv** [comment]
sprawdziłem szybko po VPN'ie zdalnym bo nie ma mnie teraz przy kompie i tak:
dla materiału: https://vod.tvp.pl/video/bolek-i-lolek,w-krolestwie-posejdona,34720453
ID: 34720453;
po wejsciu na materiał pojawia się filmik z informacją o tym ze materiał niedostepny w Twoim kraju, 

i teraz....

https://pastebin.com/raw/KGKQN71q tutaj kod html.

ale.... 

nie wiem czy to cokolwiek da, bo zarówno dla:

https://apivod.tvp.pl/tv/video/34720340

jak i 

https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=34720340

oraz

https://www.tvp.pl/shared/cdn/tokenizer_v2.php?object_id=34720340

nie wrozy aby mozna było wyciagnac materiał... 

@zacny

**Comment by xxcriticxx** [comment]
@funplayertv nie moge tego za bardzo skopiowac

![Capture](https://user-images.githubusercontent.com/15007183/59841669-ce404380-9322-11e9-866f-e11270df33d5.PNG)

**Comment by funplayertv** [comment]
@xxcriticxx  klikasz prawym klawiszem na to co masz zaznaczone i wybierasz kopiuj wew. wezeł albo jakos tak

**Comment by zacny** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} @funplayertv wrzuć proszę jeszcze zwrotkę od tokenizera                                                                                                                                                                                                                                                                                                                                                   Od: notifications@github.comWysłano: 20 czerwca 2019 12:15Do: voddownloader@noreply.github.comOdp. do: reply@reply.github.comDW: fabian.zawicki@gmail.com; mention@noreply.github.comTemat: Re: [zacny/voddownloader] wiadomosci.tvp.pl (#17)  @funplayertv nie moge tego za bardzo skopiowac


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by funplayertv** [comment]
> {
>     "url":"http://s.tvp.pl/files/player/video/material_niedostepny.mp4",
>     "status":"OK",
>     "videoId":34720340,
>     "platform":"sdt-v2",
>     "userIp":"178.62.206.93",
>     "adaptive":false,
>     "live":false,
>     "title":"Duch zamku Lorda Mc Intosha",
>     "duration":618,
>     "countryIsDefault":false,
>     "mimeType":"unknown",
>     "ads_enabled":false,
>     "payment_type":0,
>     "distribution_model":"AVOD",
>     "formats":[
>         {
>             "mimeType":"video/mp4",
>             "totalBitrate":1750000,
>             "videoBitrate":0,
>             "audioBitrate":0,
>             "adaptive":false,
>             "downloadable":false,
>             "url":"http://s.tvp.pl/files/player/video/material_niedostepny.mp4"
>         }
>     ]
> }
> 
>

**Comment by zacny** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Wygląda, że serwis weryfikuje ip użytkownika. W tym wypadku zostaje tylko vpn. Opera ma jakiś w standardzie, czy działa nie wiem. Wieczorem sprawdzę to jeszcze, ale raczej nic z tym się nie da zrobić. Może wstydzą się tego udostępnić za granicą, ja bym się w każdym razie wstydził 😀                                                                                                                                                                                                                                                                                                                                                   Od: notifications@github.comWysłano: 20 czerwca 2019 12:32Do: voddownloader@noreply.github.comOdp. do: reply@reply.github.comDW: fabian.zawicki@gmail.com; mention@noreply.github.comTemat: Re: [zacny/voddownloader] wiadomosci.tvp.pl (#17)  
{
"url":"http://s.tvp.pl/files/player/video/material_niedostepny.mp4",
"status":"OK",
"videoId":34720340,
"platform":"sdt-v2",
"userIp":"178.62.206.93",
"adaptive":false,
"live":false,
"title":"Duch zamku Lorda Mc Intosha",
"duration":618,
"countryIsDefault":false,
"mimeType":"unknown",
"ads_enabled":false,
"payment_type":0,
"distribution_model":"AVOD",
"formats":[
{
"mimeType":"video/mp4",
"totalBitrate":1750000,
"videoBitrate":0,
"audioBitrate":0,
"adaptive":false,
"downloadable":false,
"url":"http://s.tvp.pl/files/player/video/material_niedostepny.mp4"
}
]
}


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xxcriticxx** [comment]
@zacny / @funplayertv nie da rady zamienić IP na fake pl ip?

**Comment by xxcriticxx** [comment]
albo zrobić serwera po srodku?

**Comment by xxcriticxx** [comment]
to samo jest na player a tam idzie pobrac material 

test link:
https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114

![Capture9](https://user-images.githubusercontent.com/15007183/59844446-e87d2000-9328-11e9-8fcd-dca101126573.PNG)
![Capture8](https://user-images.githubusercontent.com/15007183/59844455-ed41d400-9328-11e9-93ba-4923bc64ab04.PNG)

**Comment by xxcriticxx** [comment]
@zacny / @funplayertv dziękuję za pomoc i świetną wtyczkę

**Comment by HerMajestyDrMona** [comment]
Nie chcę reklamować, ale...
https://stacksocial.com/sales/ivacy-vpn-lifetime-subscription-5?aid=a-9elzb748
Kod promocyjny: DN40
Obniża cenę do $24.00. Według mnie warto, zwłaszcza że licencja dożywotnia.
Od dawien dawna mają te oferty dożywotnie i nie zapowiada się aby się zwijali. A cena mniejsza niż za roczną subskrypcję u konkurencji.

**Comment by xxcriticxx** [comment]
@HerMajestyDrMona lol

**Comment by zacny** [comment]
@xxcriticxx
Oczywiście, że można postawić serwer, który miałby odpowiednie ip i przekazywał dalej co trzeba. Są to już jednak koszty. Poza tym skrypt przekroczyłby już raczej pewne bariery prawne.

**Comment by funplayertv** [comment]
Dokładnie, a samemu możesz użyć np HOLA Czy innej wtyczki do przeglądarki i powinno działać :)

**Comment by xxcriticxx** [comment]
dobra panowie super dzięki zrobię test z vpn

**Comment by xxcriticxx** [comment]
zamykam
